apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - resources/ALB_controller.yaml
#  - resources/external-dns.yaml
patches:
  - path: resources/patch_ingclass.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: IngressClass
      name: alb
