apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  labels:
    app: sidecar-injector
    install.operator.istio.io/owning-resource: unknown
    istio.io/rev: 1-15-0
    istio.io/tag: prod-stable
    operator.istio.io/component: Pilot
    release: istio
  name: istio-revision-tag-prod-stable
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvRENDQWVTZ0F3SUJBZ0lRV0hJWS96MjFGSElXZ016Smo0TjJ6ekFOQmdrcWhraUc5dzBCQVFzRkFEQVkKTVJZd0ZBWURWUVFLRXcxamJIVnpkR1Z5TG14dlkyRnNNQjRYRFRJek1ESXdPVEU1TlRZME0xb1hEVE16TURJdwpOakU1TlRZME0xb3dHREVXTUJRR0ExVUVDaE1OWTJ4MWMzUmxjaTVzYjJOaGJEQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNYnh0RU9lOFlDa3Z5UmQ0RnV0OWlmOXNvYzIwdzRZZXh2d0l0eXQKTkxvUjhlS0FiUncrK1RzdG51d1RkVFMyZDlDYXllc0RXdzVBYmtsMGsxcWZ1VTU4WlJvYmxQM1lOQThXa1I1RApNVEFJMTNFUUgxb04relZtMjFOWlVndTlpTXNOaGYwS0FXZ0YwUWhuaHlMUlZmWW9GK0dyeFBXMVpnUi9Ga1hsCnBhd24wU0xsK3RzOGt3RkdudkJldTZka1ZkTmR3T3plMDRzVzJ3SVp5eEp6eXZqTVlCaXZkOEhzZ0tya0dqZS8KQ21lbW55T050YmJyRTVMck5WZlBhbXlYWUUvUzZmU2JoeWhWZ05XekNVOHBvM3BDYUdZVEgwVEhjeXo0R1ltcApQbWdBUURYQUFIRUtWYVcrbm9XVFlPVlRGTmJnMW9zT01ZN1RpVjZFRG14bDlVc0NBd0VBQWFOQ01FQXdEZ1lEClZSMFBBUUgvQkFRREFnSUVNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGSGFFT0liZGZ3QjEKQUJReUg3aUVoZHFTZ3prVE1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0duTkhPRTF2T2RETytGdTRDSlp4ZQp2NGpyYVFVbG4xTHBEMWNGYVdaRTJhYjhPNUN6RlVyaG9EcjRBaGVFVnM4QmtnM0FLZWFGajVWSWhEcGR6RzRZCnBxWXJPbUl2bTF2VCtxdlhqdjRRS3VOVE96RW1xMEdyamRnT0Yycy91cGdMQTVDaXlXdWxLaW83OHhkUlBSbzIKWVNOV2lHWFRubi9VR1NFS3Y3WWdaUkNaMWcxSDk1cTNNc0tnVTI2Q2ttUnU5YklPVHlTRUtoNVUyMUdGUFF6TApVQmVaMkM0ZGl5bmFCaGk1T1RWYi9Ncmh3RzdqR2lSbjl1b2daV0cwV2J3RXppRWRRRXYvK0NzWlVDMkRUZVA4ClVER1I1MWZwWS9UTnpINmYzekFWemg4eGVqdkFwWlhuSUc4K0NpejYwOWZIRXI3ZXBYLzB2QWtiUWxVWEVKaUQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: istiod-1-15-0
      namespace: istio-system
      path: /inject
      port: 443
  failurePolicy: Fail
  name: rev.namespace.sidecar-injector.istio.io
  namespaceSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: In
      values:
      - prod-stable
    - key: istio-injection
      operator: DoesNotExist
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: NotIn
      values:
      - "false"
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvRENDQWVTZ0F3SUJBZ0lRV0hJWS96MjFGSElXZ016Smo0TjJ6ekFOQmdrcWhraUc5dzBCQVFzRkFEQVkKTVJZd0ZBWURWUVFLRXcxamJIVnpkR1Z5TG14dlkyRnNNQjRYRFRJek1ESXdPVEU1TlRZME0xb1hEVE16TURJdwpOakU1TlRZME0xb3dHREVXTUJRR0ExVUVDaE1OWTJ4MWMzUmxjaTVzYjJOaGJEQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNYnh0RU9lOFlDa3Z5UmQ0RnV0OWlmOXNvYzIwdzRZZXh2d0l0eXQKTkxvUjhlS0FiUncrK1RzdG51d1RkVFMyZDlDYXllc0RXdzVBYmtsMGsxcWZ1VTU4WlJvYmxQM1lOQThXa1I1RApNVEFJMTNFUUgxb04relZtMjFOWlVndTlpTXNOaGYwS0FXZ0YwUWhuaHlMUlZmWW9GK0dyeFBXMVpnUi9Ga1hsCnBhd24wU0xsK3RzOGt3RkdudkJldTZka1ZkTmR3T3plMDRzVzJ3SVp5eEp6eXZqTVlCaXZkOEhzZ0tya0dqZS8KQ21lbW55T050YmJyRTVMck5WZlBhbXlYWUUvUzZmU2JoeWhWZ05XekNVOHBvM3BDYUdZVEgwVEhjeXo0R1ltcApQbWdBUURYQUFIRUtWYVcrbm9XVFlPVlRGTmJnMW9zT01ZN1RpVjZFRG14bDlVc0NBd0VBQWFOQ01FQXdEZ1lEClZSMFBBUUgvQkFRREFnSUVNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGSGFFT0liZGZ3QjEKQUJReUg3aUVoZHFTZ3prVE1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0duTkhPRTF2T2RETytGdTRDSlp4ZQp2NGpyYVFVbG4xTHBEMWNGYVdaRTJhYjhPNUN6RlVyaG9EcjRBaGVFVnM4QmtnM0FLZWFGajVWSWhEcGR6RzRZCnBxWXJPbUl2bTF2VCtxdlhqdjRRS3VOVE96RW1xMEdyamRnT0Yycy91cGdMQTVDaXlXdWxLaW83OHhkUlBSbzIKWVNOV2lHWFRubi9VR1NFS3Y3WWdaUkNaMWcxSDk1cTNNc0tnVTI2Q2ttUnU5YklPVHlTRUtoNVUyMUdGUFF6TApVQmVaMkM0ZGl5bmFCaGk1T1RWYi9Ncmh3RzdqR2lSbjl1b2daV0cwV2J3RXppRWRRRXYvK0NzWlVDMkRUZVA4ClVER1I1MWZwWS9UTnpINmYzekFWemg4eGVqdkFwWlhuSUc4K0NpejYwOWZIRXI3ZXBYLzB2QWtiUWxVWEVKaUQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: istiod-1-15-0
      namespace: istio-system
      path: /inject
      port: 443
  failurePolicy: Fail
  name: rev.object.sidecar-injector.istio.io
  namespaceSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: DoesNotExist
    - key: istio-injection
      operator: DoesNotExist
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: NotIn
      values:
      - "false"
    - key: istio.io/rev
      operator: In
      values:
      - prod-stable
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
