apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: book-app

commonLabels:
  app.kubernetes.io/name: book-app
  app.kubernetes.io/component: server
  app.kubernetes.io/part-of: infrastructure-testing
  app.beyondtrust.com/team: sre
  app.beyondtrust.com/tier: tier-4


resources:
  - resources/namespace.yaml
  - resources/deployment.yaml
  - resources/service.yaml
  - resources/service_account.yaml
  - resources/bookinfo-gateway.yaml
