apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
  labels:
    argo.testing.com/deployment-environment: staging-tooling
spec:
  description: "App of App bootstraps for ArgoCD"
  sourceRepos:
  - git@github.com:fixer-coder/argocdProject.git
  destinations:
  - namespace: argocd 
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: 'argoproj.io'
    kind: ApplicationSet
  - group: 'argoproj.io'
    kind: AppProject
  - group: 'argoproj.io'
    kind: Application
