apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alpha-canary

commonLabels:
  app.kubernetes.io/name: alpha-canary
  app.kubernetes.io/component: server
  app.kubernetes.io/part-of: infrastructure-testing
  app.beyondtrust.com/team: sre
  app.beyondtrust.com/tier: tier-4


resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - rollout.yaml
#  - virtual-service.yaml
