apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-rollouts

resources:
  - https://github.com/argoproj/argo-rollouts/manifests/cluster-install?ref=v1.2.1

images:
  - name: quay.io/argoproj/argo-rollouts
    newTag: v1.2.1

patchesJson6902:
  - path: patches/argo-rollouts-controller-deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: argo-rollouts
