apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Retrieved via the download page at https://github.com/bitnami-labs/sealed-secrets/releases/download/<version>/controller.yaml
  - upstream/controller.yaml

patchesJson6902:
  - path: patches/update-deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: sealed-secrets-controller

images:
  - name: quay.io/bitnami/sealed-secrets-controller
    newName: beyondtrust-docker.jfrog.io/bitnami/sealed-secrets-controller
